- id: '1581329605337'
  alias: Set theme at start
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: palms
    service: frontend.set_theme
- id: '1598510256757'
  alias: Morning
  description: ''
  trigger:
  - at: 06:00
    platform: time
  condition: []
  action:
  - device_id: 4e145bde12b94cf0bd8808b34e29b973
    domain: switch
    entity_id: switch.kaffemaskin_power
    type: turn_on
  mode: single
- id: '1603913785136'
  alias: Halloween on
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.halloween_mode
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bell/mode/cmd
      payload: halloween
  mode: single
- id: '1603916033454'
  alias: Door just opened
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: b1e52f6f191711eb833ce9370c0ab8a2
    entity_id: binary_sensor.door_main_closed
    domain: binary_sensor
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.door_just_opened
  - delay: '2'
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.door_just_opened
  mode: single
- id: '1603997986552'
  alias: Night Light
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 10
      brightness_pct: 30
    target:
      entity_id: light.outdoor_main_door
  - service: light.turn_on
    data: {}
    entity_id: light.outdoor_nude
  mode: single
- id: '1603998088469'
  alias: Night Light End
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.outdoor_main_door
  - service: light.turn_off
    data: {}
    entity_id: light.outdoor_nude
  mode: single
- id: '1603998846225'
  alias: Increase doorlight
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: b1e52f6f191711eb833ce9370c0ab8a2
    entity_id: binary_sensor.door_main_closed
    domain: binary_sensor
  condition:
  - condition: and
    conditions:
    - condition: sun
      before: sunrise
      after: sunset
    - condition: state
      state: 'on'
      entity_id: light.outdoor_main_door
  action:
  - service: light.turn_on
    entity_id: light.outdoor_main_door
    data:
      brightness: 80
      transition: 1
  mode: single
- id: '1604082858826'
  alias: Increase doorlight (Dupliser)
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: b1e52f6f191711eb833ce9370c0ab8a2
    entity_id: binary_sensor.door_main_closed
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - service: light.turn_on
    entity_id: light.outdoor_main_door
    data:
      brightness: 80
      transition: 1
  mode: single
- id: '1604159418109'
  alias: Halloween off
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.halloween_mode
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: bell/mode/cmd
      payload: normal
  mode: single
- id: '1604919943124'
  alias: Matilde Alarm
  description: ''
  trigger:
  - platform: template
    value_template: '{% set currentTimeInMinutes = ((states(''sensor.time'')[:2] |
      float) * 60) + (states(''sensor.time'')[3:5] | float) - (states(''sensor.time'')
      | float) %} {% set alarmTimeInMinutes = ((states(''input_datetime.matilde_alarm_datetime'')[:2]
      | float) * 60) + (states(''input_datetime.matilde_alarm_datetime'')[3:5] | float)
      - (states(''input_number.matilde_alarm_duration'') | float) %} {{ currentTimeInMinutes
      == alarmTimeInMinutes }}'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.matilde_alarm_select
      state: En gang
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.matilde_alarm_select
        state: Hverdager når hjemme
      - condition: template
        value_template: '{{ now().weekday() < 5 }}'
      - condition: state
        entity_id: person.matilde
        state: home
  action:
  - service: script.matilde_alarm
    data: {}
    entity_id: script.matilde_alarm
  mode: single
- id: '1609766359131'
  alias: Garage open notofocation
  description: ''
  trigger:
  - platform: state
    entity_id: cover.garage_gate
    to: open
    for: 00:10:00
    from: '*'
  condition: []
  action:
  - service: notify.mobile_app_martin_mob
    data:
      message: Åpen i 10 minutter
      title: Garasje
  mode: single
- id: '1614154375154'
  alias: Growth light timer
  description: ''
  trigger:
  - platform: time
    at: input_datetime.flower_growth_lights_washingroom_start_time
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.washing_room_growth
  - wait_for_trigger:
    - platform: time
      at: input_datetime.flower_growth_lights_washingroom_end_time
  - service: light.turn_off
    data: {}
    entity_id: light.washing_room_growth
  mode: single
- id: '1622493340610'
  alias: Ring bell
  description: ''
  trigger:
  - platform: mqtt
    topic: bell/ring/toggle
    payload: do
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        after: '19:00'
        before: 07:00
      sequence:
      - service: script.toggle
        target:
          entity_id: script.ring_bell_night
        data: {}
    default:
    - service: script.toggle
      target:
        entity_id: script.ring_bell_day
      data: {}
  mode: single
- id: '1622876089975'
  alias: Door lock main unlock - knx
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.door_lock_main
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: lock.lock
    target:
      entity_id: lock.main_door
  mode: single
- id: '1622876128430'
  alias: Door lock main lock - knx
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.door_lock_main
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: lock.unlock
    target:
      entity_id: lock.main_door
  mode: single
- id: '1625170397687'
  alias: Climate heating on
  description: cooling/heating pump and valves based on knx controller cooling status
  trigger:
  - platform: state
    entity_id: switch.heating_toggle_cooling
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.heating_cooling_valves
      - switch.heating_cooling_pump
  mode: single
- id: '1625170463811'
  alias: Climate cooling on
  description: cooling/heating pump and valves based on knx controller cooling status
  trigger:
  - platform: state
    entity_id: switch.heating_toggle_cooling
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.heating_cooling_pump
      - switch.heating_cooling_valves
  mode: single
- id: '1625428976440'
  alias: Close garage
  description: ''
  trigger:
  - platform: time
    at: '21:00'
  - platform: time
    at: '22:00'
  - platform: time
    at: '23:00'
  - platform: time
    at: 00:00
  - platform: time
    at: 01:00
  - platform: time
    at: 02:00
  - platform: time
    at: 03:00
  - platform: time
    at: 04:00
  - platform: time
    at: 05:00
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_gate
  mode: single
- id: '1634837128615'
  alias: Main door opened
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.main_door_closed
    to: 'on'
    from: 'off'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.outdoor_main_door
        state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.outdoor_main_door
        data:
          brightness_step_pct: 30
      - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.main_door_closed
          from: open
          to: closed
          for:
            hours: 0
            minutes: 10
            seconds: 0
            milliseconds: 0
      - service: light.turn_on
        target:
          entity_id: light.outdoor_main_door
        data:
          brightness_step_pct: -30
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: light.coridor
        state: 'off'
      - condition: and
        conditions:
        - condition: time
          after: 06:00
          before: '19:00'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.coridor
        data:
          brightness_pct: 100
    default: []
  mode: single
- id: '1643977604539'
  alias: urn On Living Room TV with WakeOnLan
  description: Turn On Living Room TV with WakeOnLan
  trigger:
  - platform: device
    device_id: 7df70d0f9a325efa7425998e739d48e5
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 64:95:6c:14:0c:4c
  mode: single
