- id: '1581329605337'
  alias: '[System] Hass Started'
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: palms
    service: frontend.set_theme
- id: '1595059870707'
  alias: Lock main door
  description: ''
  trigger:
  - entity_id: binary_sensor.door_lock_main
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: lock.mqtt_lock
    service: lock.lock
- id: '1595059955329'
  alias: Unlock main door
  description: ''
  trigger:
  - entity_id: binary_sensor.door_lock_main
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: lock.mqtt_lock
    service: lock.unlock
- id: '1598510256757'
  alias: Morning
  description: ''
  trigger:
  - at: 06:00
    platform: time
  condition: []
  action:
  - device_id: 4e145bde12b94cf0bd8808b34e29b973
    domain: switch
    entity_id: switch.kaffemaskin_power
    type: turn_on
  mode: single
- id: '1600064405166'
  alias: Ring bell day
  description: ''
  trigger:
  - payload: do
    platform: mqtt
    topic: bell/ring/toggle
  condition:
  - after: 06:00
    before: '19:00'
    condition: time
  action:
  - data: {}
    entity_id: script.ring_bell_day
    service: script.toggle
  mode: single
