# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  time_zone: Europe/Oslo
  media_dirs:
    local: /media
  external_url: !secret http_base_url
  internal_url: "http://192.168.1.2:8123"
# Text to speech
  customize: !include customize.yaml


tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml

http:
  # Removed due to NGINX Addon
  #  ssl_certificate: /ssl/fullchain.pem
  #  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret my_proxy
  cors_allowed_origins:
    - https://api.home-connect.com


mqtt: !include mqtt.yaml

# cover:
#   - platform: mqtt
#     name: garage_gate
#     command_topic: "garage/gate/cmd"
#     state_topic: "garage/gate/state"
#     state_open: "open"
#     state_opening: "opening"
#     state_closed: "closed"
#     state_closing: "closing"
#     state_stopped: "stopped"
#     optimistic: false
#     qos: 0

media_player:
# !include mediaplayer.yaml

knx: !include knx.yaml
# config_file: 'xknx.yaml'

climate: !include climate.yaml

light: !include lights.yaml

frontend:
  themes: !include_dir_merge_named themes

# lovelace_gen:

lovelace:
  mode: yaml
  resources: !include lovelace/hacs-resources.yaml

# huahuacaocao:
# username: !secret huahuacaocao_user
# password: !secret huahuacaocao_password
# region: EU

# home_connect:
#   client_id: !secret homeconnect_client_id
#   client_secret: !secret homeconnect_client_secret

# spotify:
#   client_id: !secret spotify_client_id
#   client_secret: !secret spotify_client_secret

sensor: !include sensors.yaml

# binary_sensor: !include binary_sensors.yaml

# utility_meter: !include utility_meter.yaml

modbus:
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 9600
  stopbits: 1
  bytesize: 8
  parity: N


# access_control:

panel_iframe:
  lockmaster:
    title: "Lockmaster"
    url: "https://doorcontrol.lvh.duckdns.org"


template: !include templates.yaml


wake_on_lan:

# webostv:
#   host: 192.168.1.199
#   name: Living Room TV
#   turn_on_action:
#     service: wake_on_lan.send_magic_packet
#     data:
#       mac: 64:95:6c:14:0c:4c
#   customize:
#     sources:
#       - NRK TV
#       - TV 2 Play
#       - Netflix
#       - HBO Max
#       - Disney+
#       # - Amazon Prime
#       - Youtube
#       - Spotify - Music and Podcasts
#       - HDMI 2

google_assistant: !include google_assistant.yaml

rest: !include rest.yaml
 