- platform: group
  name: g_playing_room
  entities:
    - light.playing_room_1
    - light.playing_room_2
    - light.playing_room_3

- platform: group
  name: g_downstairs
  entities:
    - light.coridor
    - light.bathroom_d
    - light.washing_room
    - light.wardrobe
    - light.utility
    - light.bedroom_ludvig
    - light.bedroom_lila
    - light.bedroom_adult
    - light.playing_room
    
- platform: group
  name: g_upstairs
  entities:
    - light.kitchen_roof     
    - light.kitchen_island   
    - light.kitchen_bench  
    - light.kitchen_manhattan
    - light.kitchen_dining   
    - light.living_room_tv   
    - light.hallway_stairs   
    - light.hallway_wall     
    - light.office_roof  
    - light.bathroom_u_mirror  
    - light.bathroom_u_roof  
    - light.bathroom_u_pend  
    - light.walk_in          
    - light.bedroom_matilde  

- platform: group
  name: g_outdoor
  entities:
    - light.outdoor_main_door
    - light.outdoor_nude

- platform: group
  name: g_all
  entities:
      - light.g_downstairs
      - light.g_upstairs
      - light.g_outdoor

- platform: group
  name: g_bathroom_u
  entities:
    - light.bathroom_u_mirror  
    - light.bathroom_u_roof  
    - light.bathroom_u_pend 

- platform: group
  name: g_living_area
  entities:
    - light.kitchen_roof     
    - light.kitchen_island   
    - light.kitchen_manhattan
    - light.kitchen_dining   
    - light.living_room_tv   
    - light.hallway_stairs   
    - light.hallway_wall

- platform: group
  name: g_kitchen_area
  entities:
    - light.kitchen_roof     
    - light.kitchen_island   
    - light.kitchen_manhattan
    - light.kitchen_dining     