- platform: mqtt
  name: main_door
  command_topic: "door/main/cmd"
  state_topic: "door/main/state"
  optimistic: false
  qos: 0

- platform: mqtt
  name: garage_door
  command_topic: "door/garage/cmd"
  state_topic: "door/garage/state"
  optimistic: false
  qos: 0

- platform: mqtt
  name: workshop_door
  command_topic: "door/workshop/cmd"
  state_topic: "door/workshop/state"
  optimistic: false
  qos: 0