- platform: mqtt
  name: main_door
  command_topic: "door/1/cmd"
  state_topic: "door/1/state"
  optimistic: false
  qos: 0

- platform: mqtt
  name: garage_door
  command_topic: "door/2/cmd"
  state_topic: "door/2/state"
  optimistic: false
  qos: 0

- platform: mqtt
  name: shed_door
  command_topic: "door/3/cmd"
  state_topic: "door/3/state"
  optimistic: false
  qos: 0