title: Home
background: var(--background-image)
views:
  - !include lovelace/00_home_view.yaml
  # - !include lovelace/10_home_info_view.yaml
  - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_climate_view.yaml
#  - !include lovelace/40_cooking_view.yaml
  - !include lovelace/50_media_view.yaml
  - !include lovelace/60_plants_view.yaml
  - !include lovelace/80_energy_view.yaml
  - !include lovelace/90_scenes_and_modes.yaml
  - !include lovelace/100_christmas.yaml
  - !include lovelace/300_matilde_view.yaml
  # - !include lovelace/31_valve_graphs.yaml
  # - !include lovelace/40_camera_view.yaml
  # - !include lovelace/3d_printer.yaml
  # - !include lovelace/80_automations_view.yaml
  # - !include lovelace/99_settings_view.yaml
  # - !include lovelace/102_nest_dashboard.yaml

  # - !include lovelace/media.yaml
  # - !include lovelace/isa.yaml
  # - !include lovelace/stefan.yaml
  # - !include lovelace/climate.yaml
  # - !include lovelace/surveillance.yaml
  # - !include lovelace/cats.yaml